# Generated by Django 3.1.2 on 2020-10-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeshiftrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshiftrecords',
            name='week',
            field=models.CharField(choices=[('W1', 'WEEK1'), ('W2', 'WEEK2'), ('W3', 'WEEk3'), ('W4', 'WEEK4')], default='W1', max_length=2),
        ),
    ]
