# Generated by Django 3.1.2 on 2020-10-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeeshiftrecords_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeshiftrecords',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
