# Generated by Django 3.1.2 on 2020-10-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20201019_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshiftrecords',
            name='month',
            field=models.CharField(choices=[('JAN', 'JANUARY'), ('FEB', 'FEBRUARY'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MAY'), ('JUN', 'JUNE'), ('JUL', 'JULY'), ('AUG', 'AUGUST'), ('SEP', 'SEPTEMBER'), ('OCT', 'OCTOBER'), ('NOV', 'NOVEMBER'), ('DEC', 'DECEMBER')], default='JAN', max_length=3),
        ),
        migrations.AlterField(
            model_name='employeeshiftrecords',
            name='week',
            field=models.CharField(choices=[('W1', 'WEEK1'), ('W2', 'WEEK2'), ('W3', 'WEEk3'), ('W4', 'WEEK4')], max_length=2),
        ),
    ]
