# Generated by Django 3.1.2 on 2020-10-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20201019_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeshiftrecords',
            name='month',
            field=models.CharField(choices=[('01', 'JANUARY'), ('02', 'FEBRUARY'), ('03', 'MARCH'), ('04', 'APRIL'), ('05', 'MAY'), ('06', 'JUNE'), ('07', 'JULY'), ('08', 'AUGUST'), ('09', 'SEPTEMBER'), ('10', 'OCTOBER'), ('11', 'NOVEMBER'), ('12', 'DECEMBER')], default='01', max_length=2),
        ),
    ]
