# Generated by Django 3.1.2 on 2020-10-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20201019_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='shift',
        ),
    ]
