# Generated by Django 3.1.2 on 2020-10-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_employee_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifts',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='shifttype',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='startdate',
        ),
        migrations.AddField(
            model_name='shifts',
            name='description',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='shifts',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
